Next
codesandbox/dependency-seo-pages pull request #24
Opened 2021-05-18 15:01 UTC by danilowoz

2021-05-18 15:23 UTC, danilowoz commented on .eslintrc.json
>  {
Got this from Codebox repo

2021-05-19 09:13 UTC, CompuIves commented
One thing we'll need to do is change the url structure to be like this:

```
/examples/package/react
```

So that we can seamlessly replace the existing deploy, if possible 😄 .

2021-05-19 09:13 UTC, CompuIves commented on .eslintrc.json
>  {
Nice!

2021-05-19 09:17 UTC, danilowoz commented
Hey @CompuIves, as I'm using only the last slug of the path, it works either `examples/packages/react` or `packages/react`, however, in a second thought, maybe it would be better to fix the path. What do you think?

2021-05-19 15:14 UTC, CompuIves commented
The sitemap generator assumes right now that the urls are on `/example/package/:package-slug`, so that's why it would be easier to go with such a route first. Here's a sitemap generated by it: https://codesandbox.io/sitemap/dependency/sitemap.0.xml. If it would not be possible with Next.js, we can maybe do some magic in our router to make it still work 😄

2021-05-19 15:23 UTC, DannyRuchtie requested changes
Looks great I spotted 3 things 
- Load more button renders incorrect in Safari
- We miss the environment icon (if we still want them there) 
- The fonts in the footer are different from the one on the homepage
This is also in the version that is on production right now but is a bug :D 

<img width="1101" alt="Screenshot 2021-05-19 at 17 18 56" src="https://user-images.githubusercontent.com/46239581/118839623-ef22c200-b8c6-11eb-894e-28dec8fa418f.png">
<img width="1789" alt="Screenshot 2021-05-19 at 17 20 54" src="https://user-images.githubusercontent.com/46239581/118839631-f0ec8580-b8c6-11eb-8cfb-dd508a848216.png">

2021-06-02 12:23 UTC, DannyRuchtie approved these changes
looking good

2021-06-07 15:19 UTC, CompuIves approved these changes

2021-06-07 15:22 UTC, merged